### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by qinastar** [lukas0x1/sml-pc#4]
[Sky.log](https://github.com/user-attachments/files/16348453/Sky.log)

**Comment by fishnet-technologies** [comment]
Possible VulkanHook issue, try restarting the game over and over to see if it just randomly launches with sml-pc.

**Comment by fishnet-technologies** [comment]
> same issue here, tried to restart multiple times, always crashes

try installing [VC_redist.x64.exe](https://github.com/TheSR007/That_Sky_Mod_Release/releases/download/1.9.1/VC_redist.x64.exe) if you haven't already, that may fix your issue.

**Comment by fishnet-technologies** [comment]
Closed for inactivity
